version: "3.7"
volumes:
  coffee-diary:
    external: true
  pg-admin-coffee:
    external: true
services:
  react:
    image: node:latest
    command: npm start
    working_dir: /coffee_fe
    volumes:
      - ./ghi/coffee_fe:/coffee_fe
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
    ports:
      - "3000:3000"
  coffee_project:
    build:
      context: ./coffee_project
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://rgibbs:secretpass@db/coffee_db
      WAIT_HOSTS: db:5432
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./coffee_project:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secretpass
      POSTGRES_USER: rgibbs
      POSTGRES_DB: coffee_db
    ports:
      - "15432:5432"
    volumes:
      - coffee-diary:/var/lib/postgresql/data
  pg-admin-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin-coffee:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_DISABLE_POSTFIX: 1
