# Generated by Django 4.0.3 on 2023-02-01 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Creamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('burrs', models.CharField(default='stock', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sweetener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('water_quantity_g', models.PositiveIntegerField()),
                ('baking_soda_quantity_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('epsom_salt_quantity_g', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture_url', models.URLField(max_length=500)),
                ('roast_date', models.DateField()),
                ('roast_level', models.CharField(max_length=100)),
                ('roast_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('process', models.CharField(max_length=200)),
                ('single_origin', models.BooleanField(default=True)),
                ('note1', models.CharField(max_length=200)),
                ('note2', models.CharField(blank=True, max_length=200, null=True)),
                ('note3', models.CharField(blank=True, max_length=200, null=True)),
                ('note4', models.CharField(blank=True, max_length=200, null=True)),
                ('origin1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin1', to='coffee.origin')),
                ('origin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin2', to='coffee.origin')),
                ('origin3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin3', to='coffee.origin')),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roaster', to='coffee.roaster')),
            ],
        ),
        migrations.CreateModel(
            name='BrewedCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_brewed', models.DateField()),
                ('coffee_dose_g', models.PositiveSmallIntegerField()),
                ('liquid_yield_g', models.PositiveSmallIntegerField()),
                ('total_brew_time_s', models.PositiveSmallIntegerField()),
                ('grind_size', models.SmallIntegerField()),
                ('water_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('preinfusion', models.BooleanField(default=False)),
                ('preinfusion_time_s', models.SmallIntegerField(blank=True, null=True)),
                ('pressure_bar', models.SmallIntegerField(blank=True, null=True)),
                ('bloom', models.BooleanField(default=False)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bean', to='coffee.coffeebean')),
                ('brewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brewer', to='coffee.brewer')),
                ('creamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creamer', to='coffee.creamer')),
                ('grinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grinder', to='coffee.grinder')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='method', to='coffee.brewmethod')),
                ('sweetener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sweetner', to='coffee.sweetener')),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water', to='coffee.waterblend')),
            ],
        ),
    ]
