# Generated by Django 4.0.3 on 2023-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebean',
            name='elevation1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='elevation2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
