# Generated by Django 4.0.3 on 2023-02-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffeebean_elevation1_coffeebean_elevation2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='process',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
