# Generated by Django 4.0.3 on 2023-02-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_coffeebean_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterblend',
            name='baking_soda_quantity_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterblend',
            name='epsom_salt_quantity_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
