# Generated by Django 4.0.3 on 2023-02-02 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_waterblend_baking_soda_quantity_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewedcoffee',
            name='date_brewed',
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='date_time_brewed',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 23, 47, 51)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewedcoffee',
            name='creamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creamer', to='coffee.creamer'),
        ),
        migrations.AlterField(
            model_name='brewedcoffee',
            name='sweetener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sweetner', to='coffee.sweetener'),
        ),
    ]
