# Generated by Django 4.0.3 on 2023-02-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_remove_brewedcoffee_date_brewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewedcoffee',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brewer', to='coffee.brewer'),
        ),
        migrations.AlterField(
            model_name='brewedcoffee',
            name='grinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grinder', to='coffee.grinder'),
        ),
        migrations.AlterField(
            model_name='brewedcoffee',
            name='water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='water', to='coffee.waterblend'),
        ),
    ]
