# Generated by Django 4.0.3 on 2023-02-15 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_brewedcoffee_brewer_alter_brewedcoffee_grinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewedcoffee',
            name='acidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='bitterness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='body',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='brightness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='clarity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='general_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='sweetness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
