# Generated by Django 4.0.3 on 2023-02-20 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0007_brewedcoffee_acidity_brewedcoffee_bitterness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewedcoffee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
