# Generated by Django 4.0.3 on 2023-03-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_brewedcoffee_user_brewer_user_coffeebean_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewedcoffee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='brewer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coffeebean',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creamer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grinder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sweetener',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterblend',
            name='user',
        ),
    ]
