# Generated by Django 3.2.16 on 2023-03-15 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0009_remove_brewedcoffee_user_remove_brewer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterblend',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
