# Generated by Django 3.2.16 on 2023-03-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0010_waterblend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grinder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grinder', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterblend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterblend', to=settings.AUTH_USER_MODEL),
        ),
    ]
