# Generated by Django 3.2.16 on 2023-03-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0011_auto_20230315_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brewer', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
