# Generated by Django 3.2.16 on 2023-03-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_brewedcoffee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeebean',
            name='roast_date',
        ),
        migrations.AddField(
            model_name='brewedcoffee',
            name='roast_date',
            field=models.DateField(default="2023-1-28"),
            preserve_default=False,
        ),
    ]
